### ISSUE TITLE
Adblock breaks extension

### ISSUE THREAD

**Issue by Vishnu-Thirumalai** [keifufu/WebNowPlaying-Redux#5] opened 2023-03-04 19:47 UTC
Duplicate of https://github.com/tjhrulz/WebNowPlaying-BrowserExtension/issues/54

Can be fixed by adding the extension to the brave filter list: as repo is locked I couldn't update the README, here's the instructions: 

### If you use an adblocker

Some adblockers block requests to localhost, which breaks this plugin. To fix this, add the following to your adblock's filter list: 

```
@@||localhost^8974
@@||localhost^8698
```

Here's where to find your filter list:
 - Brave - brave://settings/shields/filters
 - Ublock Origin
     - Open the extension settings (different on each browser)
     - Go to the 'My Filters' tab

**Comment by keifufu** [comment] 2023-03-06 05:54
Thanks for letting me know.
Is there a way to allow all ports through localhost? I don't see why I would recommend only allowing a certain few when more adapters are likely to be added in the future and as users can add their own custom ports.

Also, I'm not sure what you meant by "repo is locked". You should be able to submit a pull request.

**Comment by Vishnu-Thirumalai** [comment] 2023-03-06 17:41
There is a way (just add @@||localhost), but the reason localhost is blocked in the first place is due to security reasons as mentioned here https://github.com/brave/brave-browser/issues/15004. 

And right sorry, I tried to push a branch but wasn't able to - will try again.

**Comment by Glasses-are-90-me** [comment] 2023-03-07 12:48
Is it possible to limit the calls for localhost if it fails, it appears to be that the blocked localhost leaks memory at an alarming rate if left to continously error out and retry. for allot of people they will have extension sync on computers without rainmeter
![image](https://user-images.githubusercontent.com/17042136/223426208-ccee8557-e443-47d3-8e17-9dbb0de21439.png)

**Comment by keifufu** [comment] 2023-03-07 14:52
@Glasses-are-90-me Yes, although I'm not sure why you're commenting on this issue about another issue, regardless:
- I've fixed this memory leak earlier today. Both the chrome and firefox webstore already have the updated version (1.0.1)
- It was caused by simply not closing the sockets correctly before retrying to connect, and as it turns out, browsers behave really freaky after you have 255 websockets open at a time.

**Closed** 2023-03-10 09:16 UTC
