### ISSUE TITLE
Images from other webpages that title

### ISSUE THREAD

**Issue by CrazyWolf13** [keifufu/WebNowPlaying-Redux#11] opened 2023-04-22 08:33 UTC
I don't know if it's jellyfin only, but if I play a video from jellyfin, the title appears just fine, but the image is just any random image from another opened webpage, the image is not connected to any media, just a random image....

**Comment by keifufu** [comment] 2023-04-22 08:42
What adapter/s are you using?

**Comment by CrazyWolf13** [comment] 2023-04-22 08:43
Rainmeter

> What adapter/s are you using?

**Comment by keifufu** [comment] 2023-04-22 08:44
It's kinda hard to know if this is the extensions or the rainmeter plugins fault.
It would be much easier to talk on discord to debug this: keifufu#3431

**Comment by keifufu** [comment] 2023-04-22 09:09
Closing this as it was most likely caused by a poorly written Rainmeter skin.
Granted, the current version of this extension that is on the webstore doesn't have great support for jellyfin covers, but that has already been improved and will be in the next version.

**Closed by keifufu** 2023-04-22 09:09 UTC
