### ISSUE TITLE
Disconnect the Adapters when no playback is detected

### ISSUE THREAD

**Issue by BLACK4585** [keifufu/WebNowPlaying-Redux#22] opened 2023-09-19 18:58 UTC
I have my Rainmeter skin configured to hide it when no adapter is being used. Using this Extension now results in always an empty, white skin on my desktop.
That's why I'm asking if it's possible to disconnect the adapters when no current playback from a supported site is detected and reconnect when a playback starts?

**Comment by keifufu** [comment] 2023-09-19 18:59
Duplicate of #20

**Closed by keifufu** 2023-09-19 18:59 UTC
